### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by kmario23** [sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#57]
Hi @sgrvinod,
  I'm experiencing `RuntimeError: CUDA error: out of memory` when I use a `batch_size` of 96-128. I can only fit 64 examples in GPU memory. But, the real issue is that the training loop works perfectly fine with `batch_size`s ranging from 96-128. It's only when the [`validate()`](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/blob/master/train.py#L119) function is called, which happens after each epoch, I get this error.

Here's the traceback for your reference:

```
Traceback (most recent call last):
  File "train.py", line 349, in <module>
    main()
  File "train.py", line 127, in main
    criterion=criterion)
  File "train.py", line 282, in validate
    scores_copy = scores.clone()
RuntimeError: CUDA error: out of memory

```
Any idea about how to fix this issue? I'm using `GTX TITAN X` which has 12GB memory.

**Comment by sgrvinod** [comment]
Hi, I'm on mobile right now, but you can try putting everything under the validate() function under "with torch.no_grad():".

def validate():
     with torch.no_grad():
          .......

**Comment by sgrvinod** [comment]
Like I've done here: https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Object-Detection/blob/master/train.py

**Comment by kmario23** [comment]
Thank you @sgrvinod! That solved the issue.
